### ISSUE TITLE
Can't flash self generated sparse images

### ISSUE THREAD

**Issue by ghost** [friendlyarm/eflasher-updater#1]
Using the "dd" tool, I read out core4418 partition images (android-partitions boot, system, data, cache).
I then converted these ext4-images to sparse images using the "img2simg" tool.
I put these sparse-image onto the eflasher-sdcard into folder "android". I.e. where the prebuilt images were stored beforehand.

eflasher gui starts writing but stops after approx. 10 sec.
Images are of not written (normally, this write takes approx. 1-2 minutes). No error message is displayed.

The prebuilt images (on the downloadable sd-cards provided by friendly arm) are the same format (sparse-images of ext4-filesystems). The output of the android build system is also the same format.

How can I flash self-generated images using eflasher?
Thanks in advance.

**Comment by friendlyarm** [comment]
You need to use https://github.com/friendlyarm/sd-fuse_s5p4418/blob/master/tools/make_ext4fs to make the img file
